[workspace]
members = [
    "crates/i2pr-sam-proto",
    "crates/i2pr-sam",
    "crates/i2pr-sam-blocking",
    "crates/i2pr-sam-ffi",
    "crates/i2pr-sam-python",
    "crates/i2pr-sam-service-tunnels",
]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.89"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = "warn"
